version: '2'

services:
  consuldta:
#    build:
#      context: hgg-ida.secrets.consul
    image: registry.haufe.io/hgg/secrets-consul:dev
    volumes:
    - "/var/consul"
    entrypoint: /bin/true

  consul:
#    build:
#      context: hgg-ida.secrets.consul
    image: registry.haufe.io/hgg/secrets-consul:dev
    ports:
    - "8300:8300"
    - "8301:8301"
    - "8301:8301/udp"
    - "8302:8302"
    - "8302:8302/udp"
    - "8400:8400"
    - "8500:8500"
    - "8600:8600"
    - "8600:8600/udp"
    volumes_from:
    - "consuldta"
    restart: "unless-stopped"
    env_file: variables.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${FLUENTD}:24224"
        fluentd-async-connect: "true""
        tag: "docker.{{.Name}}"

  vault:
#    build:
#      context: hgg-ida.secrets.vault
    image: registry.haufe.io/hgg/secrets-vault:dev
    ports:
    - "8200:8200"
    depends_on:
    - "consul"
    env_file: variables.env
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "${FLUENTD}:24224"
        fluentd-async-connect: "true""
        tag: "docker.{{.Name}}"
